---
clone_folder: c:\project\s2spice
shallow_clone: false
clone_depth: 10

image:
  - Visual Studio 2022

platform:
  - Win32

configuration: RelWithDebInfo

install:
  - set "VS_BASE=C:\Program Files\Microsoft Visual Studio\2022"
  - call "%VS_BASE%\Community\VC\Auxiliary\Build\vcvars32.bat"

  - cmd: python --version
  - cmd: python -m pip install cloudsmith-cli

build_script:
  - call .\appveyor.bat
